name: publish to npm
on:
  # mainブランチへのmergeでもトリガーされる
  # 直接のpushはbranch保護ルールで禁止している前提
  push:
    branches:
      - main
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enable Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
          registry-url: 'https://registry.npmjs.org'
          scope: '@seo4d696b75'
          always-auth : true
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Can Publish
        run : npx can-npm-publish --verbose
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Install
        run : npm install
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      # prepublishOnlyスクリプトが指定されている場合は不要
      #- name: Build
      #  run : npm run build --if-present
      #  env :
      #    NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Publish
        run : npm publish --access=public
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}